// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sannel.House.Sensor;
using Sannel.House.SensorCapture.Data;
using System;

namespace Sannel.House.SensorCapture.Data.Migrations
{
	[DbContext(typeof(DataContext))]
	[Migration("20180404205301_Inital")]
	partial class Inital
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

			modelBuilder.Entity("Sannel.House.SensorCapture.Common.SensorEntry", b =>
				{
					b.Property<Guid>("LocalId")
						.ValueGeneratedOnAdd();

					b.Property<DateTime>("CreatedDate");

					b.Property<long?>("MacAddress");

					b.Property<int>("SensorType");

					b.Property<Guid?>("Uuid");

					b.Property<double>("Value");

					b.Property<double?>("Value10");

					b.Property<double?>("Value2");

					b.Property<double?>("Value3");

					b.Property<double?>("Value4");

					b.Property<double?>("Value5");

					b.Property<double?>("Value6");

					b.Property<double?>("Value7");

					b.Property<double?>("Value8");

					b.Property<double?>("Value9");

					b.HasKey("LocalId");

					b.ToTable("SensorEntries");
				});
#pragma warning restore 612, 618
		}
	}
}
