// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sannel.House.SensorCapture.Data;

namespace Sannel.House.SensorCapture.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180503031111_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Sannel.House.Sensor.SensorEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<long?>("DeviceMacAddress");

                    b.Property<Guid?>("DeviceUuid");

                    b.Property<string>("SensorType");

                    b.Property<string>("Values");

                    b.HasKey("Id");

                    b.ToTable("SensorEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
