// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sannel.House.SensorCapture.Data;
using System;

namespace Sannel.House.SensorCapture.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Sannel.House.SensorCapture.Data.LocalSensorEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<long?>("DeviceMacAddress");

                    b.Property<Guid?>("DeviceUuid");

                    b.Property<string>("SValues");

                    b.Property<string>("SensorType");

                    b.HasKey("Id");

                    b.ToTable("SensorEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
